title: Team Lobster
logo: /assets/img/logo.png
description: ESE 5190 Final Project
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
domain: ese-519-team-lobster.github.io
url: https://ese-519-team-lobster.github.io
